# Generated by Django 4.2 on 2024-10-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
