# Generated by Django 4.2 on 2024-10-27 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_order_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="completed",
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="created", max_length=255),
        ),
    ]
